---
- hosts: localhost
  tasks:
    - name: Create a data container
      docker_container:
        name: flask_app
        image: reist/trg:latest
        command: run
    - name: nginx
      docker_container:
        name: nginx
        image: nginx:1.17.0-alpine
        ports: 80:80
        ports: 127.0.0.1:443:443
        links:
          - flask_app
        volumes: 
          - "{{ lookup('env', 'PWD') }}/nginx:/etc/nginx/conf.d:ro"
          - "{{ lookup('env', 'PWD') }}/certs:/etc/ssl:ro"
